# Generated by Django 5.1.2 on 2024-10-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spider_app", "0002_spidertask_delete_spider"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spidertask",
            old_name="country_code",
            new_name="country",
        ),
        migrations.RemoveField(
            model_name="spidertask",
            name="token",
        ),
        migrations.AddField(
            model_name="spidertask",
            name="stop_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="spidertask",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
