# Generated by Django 5.1.2 on 2024-10-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spider_app", "0003_rename_country_code_spidertask_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spidertask",
            name="data_file_path",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
